url: https://www.pavlaguitar.com
baseurl: /

# Site settings
title: Pavla Guitar
author: Pavla Lušin
email: your-email@domain.com
description: "Pavla is a professional guitar teacher based in Dublin. Reach out for private guitar lessons customised to your taste."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Dublin, Ireland

# Build settings
markdown: kramdown
permalink: pretty
